---
documentTitle : "Cave LiDAR Processing parameters"
documentAuthor: "Tanguy Racine"
dateCreated: 2024.01.17

#... Cave attributes
cave:
    caveName: "RuptDuPuits"
    fullCaveName: "Rupt du Puits"

#... Folder paths
paths:
    root: "F:/ScanLeica/from_pointcloud_to_mesh/real_data/12_RuptDuPuits"
    rawPointClouds: "raw"
    outputs: "output"
    processingFilepath: "process"
    inCloudName: "raw/RuptDuPuits.las"
    georefOutCloudName: "output/RuptDuPuits_georef.las"
    subsampledGeorefOutCloudName: "output/RuptDuPuits_subsampled_georef.las"
    globalShift: "georef/GlobalShift.txt"
    centrelines: "process/centrelines"
    log: "log.txt"

#... Initial CloudCompare processing parameters
alignment: 
    globalShift: [0, 0, 0 ]
    crs: None
    elevation: None

subsampling: 
    spatialSamplingDistance: 0.05 # smallest distance between neighbouring points in processing.
    
onsave:    
    globalShift : true 


