---
documentTitle : "Cave LiDAR Processing parameters"
documentAuthor: "Tanguy Racine"
dateCreated: 2023-08-01

#... Cave attributes
cave:
    caveName: "VersChezLeBrandt"
    fullCaveName: "Grotte de Vers Chez le Brandt"

#... Initial CloudCompare processing parameters
paths:
    root: "F:\\ScanLeica\\from_pointcloud_to_mesh\\real_data\\01_VersChezLeBrandt"
    rawPointClouds: "raw"
    outputs: "output"
    processingFilepath: "process"
    therionFiles : "therion"
    cropboxes : "process/cropped_clouds/CropBoxes.geojson"
    inCloudName: "raw/VersChezLeBrandt.las"
    georefOutCloudName: "output/VersChezLeBrandt_georef.ply"
    subsampledGeorefOutCloudName: "output/VersChezLeBrandt_subsampled_georef.las"
    globalShift: "georef/GlobalShift.txt"
    transformMatrix: "georef/TransMatrix.txt"
    centrelines: "process/centrelines"
    scanTargets: "georef/VersChezLeBrandt_ScanTargets.txt"
    therionTargets: "georef/VersChezLeBrandt_StationCoords.txt"
    log: "log.txt"
    rasterZ: "VersChezLeBrandtRasterZ"
    entranceCrop: "process/CropEntrance.poly"

entranceCropping: 
    direction: 2 # remove trees in the side view directed north (Z direction)
    polyLine: "CropEntrance.poly"
    leaveInside: False # retain everything but the trees selected.


alignment: 
    skip_rows: 1
    max_rows: 4
    usecols: [1,2,3]
    globalShift: [-526500, -198900, -1100]
    crs: "epsg:21781"
    elevation: "above sea level"

subsampling: 
    spatialSamplingDistance: 0.05 # smallest distance between neighbouring points in processing.
    
onsave:    
    globalShift : true 
